scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_launcher:
  module: dagster_k8s
  class: K8sRunLauncher
  config:
    service_account_name: dagster
    job_namespace: orchestration
    load_incluster_config: true
    job_image: dagster/dagster-k8s:1.10.20
    job_spec_config:
      activeDeadlineSeconds: 20  # 20 seconds for testing run launcher timeout
      backoffLimit: 0
    wait_timeout: 25  # Wait 25 seconds for K8s job completion before timing out

storage:
  postgres:
    postgres_db:
      username: dagster
      password: dagster
      hostname: localhost
      db_name: dagster
      port: 5432

compute_logs:
  module: dagster.core.storage.logs
  class: DefaultComputeLogManager
  config:
    base_dir: ./logs

run_monitoring:
  enabled: true
  poll_interval_seconds: 1
  max_resume_run_attempts: 0
  start_timeout_seconds: 15
  max_runtime_seconds: 5  # Global timeout for all runs (5s for testing)
  cancellation_thread_poll_interval_seconds: 1