# Base schedule configuration
# This file defines the default schedule configuration that can be overridden by environment-specific configs

schedules:
  at_01_rss_ingest:
    enabled: true
    cron_schedule: "0 * * * *"  # Every hour at :00
    default_status: "RUNNING"
    description: "RSS Ingest job - fetches RSS feeds"
    
  at_02_collect:
    enabled: true
    cron_schedule: "6 * * * *"  # Every hour at :06
    default_status: "RUNNING"
    description: "Collect job - collects data from ingested feeds"
    
  at_03_parse:
    enabled: true
    cron_schedule: "12 * * * *"  # Every hour at :12
    default_status: "RUNNING"
    description: "Parse job - parses collected data"
    
  at_04_file_filtration:
    enabled: true
    cron_schedule: "18 * * * *"  # Every hour at :18
    default_status: "RUNNING"
    description: "File Filtration job - filters parsed files"
    
  at_05_metadata_collection:
    enabled: true
    cron_schedule: "24 * * * *"  # Every hour at :24
    default_status: "RUNNING"
    description: "Metadata Collection job - collects metadata from files"
    
  at_06_media_filtration:
    enabled: true
    cron_schedule: "30 * * * *"  # Every hour at :30
    default_status: "RUNNING"
    description: "Media Filtration job - filters media files"
    
  at_07_initiation:
    enabled: true
    cron_schedule: "36 * * * *"  # Every hour at :36
    default_status: "RUNNING"
    description: "Initiation job - initiates download process"
    
  at_08_download_check:
    enabled: true
    cron_schedule: "42 * * * *"  # Every hour at :42
    default_status: "RUNNING"
    description: "Download Check job - checks download status"
    
  at_09_transfer:
    enabled: true
    cron_schedule: "48 * * * *"  # Every hour at :48
    default_status: "RUNNING"
    description: "Transfer job - transfers completed downloads"
    
  at_10_cleanup:
    enabled: true
    cron_schedule: "54 * * * *"  # Every hour at :54
    default_status: "RUNNING"
    description: "Cleanup job - cleans up temporary files"